/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import classes.Jogo;
import javax.swing.JOptionPane;
import javax.swing.ImageIcon;

/**
 *
 * @author lucca
 */
public class JogoForca extends javax.swing.JFrame {

    private static final int CRIACAO = 0;
    private static final int INICIALIZACAO = 1;
    private static final int FIMDEJOGO = 2;
    private int estado;

    private Jogo jogo;


    public JogoForca() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTFPalavra = new javax.swing.JTextField();
        jTFLetraUsada = new javax.swing.JTextField();
        jTFUltimoPalpite = new javax.swing.JTextField();
        jTFTentativas = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jTFDica = new javax.swing.JTextField();
        jBLetra = new javax.swing.JButton();
        jBPalavra = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMJogo = new javax.swing.JMenu();
        jMINovoJogo = new javax.swing.JMenuItem();
        jMAjuda = new javax.swing.JMenu();
        jMIDica = new javax.swing.JMenuItem();
        jMSair = new javax.swing.JMenu();
        jMISair = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Jogo da Forca");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        jLabel1.setText("Dica:");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder(null, "Informações", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 1, 12), new java.awt.Color(255, 0, 0)))); // NOI18N

        jLabel2.setText("Palavra:");

        jLabel3.setText("Letras Usadas:");

        jLabel4.setText("Último Palpite:");

        jLabel5.setText("Erros restantes:");

        jTFPalavra.setEditable(false);

        jTFLetraUsada.setEditable(false);

        jTFUltimoPalpite.setEditable(false);

        jTFTentativas.setEditable(false);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTFPalavra, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTFLetraUsada, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTFTentativas, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTFUltimoPalpite, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(243, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTFPalavra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTFLetraUsada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jTFUltimoPalpite, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jTFTentativas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(49, Short.MAX_VALUE))
        );

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/logotipo.jpg"))); // NOI18N

        jTFDica.setEditable(false);

        jBLetra.setText("Letra");
        jBLetra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBLetraActionPerformed(evt);
            }
        });

        jBPalavra.setText("Palavra");
        jBPalavra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBPalavraActionPerformed(evt);
            }
        });

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/forca7.jpg"))); // NOI18N

        jMJogo.setText("Jogo");

        jMINovoJogo.setText("Novo Jogo");
        jMINovoJogo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMINovoJogoActionPerformed(evt);
            }
        });
        jMJogo.add(jMINovoJogo);

        jMenuBar1.add(jMJogo);

        jMAjuda.setText("Ajuda");

        jMIDica.setText("Mostrar Dica");
        jMIDica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMIDicaActionPerformed(evt);
            }
        });
        jMAjuda.add(jMIDica);

        jMenuBar1.add(jMAjuda);

        jMSair.setText("Sair");

        jMISair.setText("Sair");
        jMISair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMISairActionPerformed(evt);
            }
        });
        jMSair.add(jMISair);

        jMenuBar1.add(jMSair);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTFDica, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jBLetra)
                                .addGap(18, 18, 18)
                                .addComponent(jBPalavra)
                                .addGap(81, 81, 81))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addContainerGap())))))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jBLetra, jBPalavra});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1)
                        .addComponent(jTFDica, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jBLetra)
                        .addComponent(jBPalavra)))
                .addGap(27, 27, 27)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jBLetra, jBPalavra});

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBLetraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBLetraActionPerformed
       
        String letras = JOptionPane.showInputDialog(this, "Qual a letra?", "Letra", 0);
        
        if (letras.length() > 1){
            JOptionPane.showMessageDialog(this, "Digite uma letra", "Aviso", 0);
            return;
        }
        
        if (!letras.matches("[^\\d]+")){
            JOptionPane.showMessageDialog(this, "Digite uma letra", "Aviso", 0);
            return;
        }
      
        if (jogo.adiciona(letras.charAt(0)) == 1) {
            jogo.adiciona(letras.charAt(0));
            jTFLetraUsada.setText(jogo.letrasUsadas());
            if (!jogo.acertos(letras.charAt(0))) {
                jogo.setTentativas();
                jTFTentativas.setText(String.valueOf(jogo.getTentativas()));
                jLabel7.setIcon(new ImageIcon(getClass().getResource(jogo.trocaImagem())));
            } else {
                jTFPalavra.setText(jogo.letrasAcertadas());
            }
        } else if (jogo.adiciona(letras.charAt(0)) == 0) {
            JOptionPane.showMessageDialog(this, "Letra já utilizada", "Aviso", 0);
        }
        perdeu();
    }//GEN-LAST:event_jBLetraActionPerformed

    private void jMINovoJogoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMINovoJogoActionPerformed
        jogo = new Jogo();
        jogo.setLetrasCertas();
        jTFPalavra.setText(jogo.letrasAcertadas());
        jTFTentativas.setText(String.valueOf(jogo.getTentativas()));
        jTFLetraUsada.setText(null);
        jTFUltimoPalpite.setText(null);
        jLabel7.setIcon(new ImageIcon(getClass().getResource(jogo.trocaImagem())));
        setEstado(1);

    }//GEN-LAST:event_jMINovoJogoActionPerformed

    private void jMISairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMISairActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jMISairActionPerformed

    private void jBPalavraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBPalavraActionPerformed
        String palavra = JOptionPane.showInputDialog(this, "Qual a palavra?", "Palavra", 0);
        jTFUltimoPalpite.setText(palavra);
        if (jogo.palavraFinal(palavra)) {
            JOptionPane.showMessageDialog(this, "Você acertou a palavra", "Vencedor", 0);
            setEstado(2);
        } else {
            JOptionPane.showMessageDialog(this, "Não é a palavra", "Tentativa", 0);
            jTFTentativas.setText(String.valueOf(jogo.getTentativas()));
            jLabel7.setIcon(new ImageIcon(getClass().getResource(jogo.trocaImagem())));
        }
        perdeu();
    }//GEN-LAST:event_jBPalavraActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        setEstado(0);
    }//GEN-LAST:event_formWindowOpened

    private void jMIDicaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMIDicaActionPerformed
        jTFDica.setText(jogo.getSorteada().getDica());
    }//GEN-LAST:event_jMIDicaActionPerformed

    public void perdeu() {
        if (jogo.perdeu()) {
            JOptionPane.showMessageDialog(this, "Você perdeu", "Derrota", 0);
            setEstado(2);
        }
    }

    public int getEstado() {
        return estado;
    }

    public void setEstado(int estado) {
        java.awt.Component[] componentes = jPanel1.getComponents();
        this.estado = estado;
        switch (estado) {
            case CRIACAO:
                for (int i = 0; i < componentes.length; i++) {
                    if (componentes[i] instanceof javax.swing.JTextField) {
                        javax.swing.JTextField texto = (javax.swing.JTextField) componentes[i];
                        texto.setText(null);
                    }
                    jMIDica.setEnabled(false);
                    jTFDica.setEnabled(false);
                    jBLetra.setEnabled(false);
                    jBPalavra.setEnabled(false);
                }
                break;
            case INICIALIZACAO:
                jMIDica.setEnabled(true);
                jTFDica.setText(null);
                jTFDica.setEnabled(true);
                jBLetra.setEnabled(true);
                jBPalavra.setEnabled(true);
                break;
            case FIMDEJOGO:
                for (int i = 0; i < componentes.length; i++) {
                    if (componentes[i] instanceof javax.swing.JTextField) {
                        javax.swing.JTextField texto = (javax.swing.JTextField) componentes[i];
                        texto.setText(null);
                    }
                    jBLetra.setEnabled(false);
                    jBPalavra.setEnabled(false);
                }
                break;

        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JogoForca.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JogoForca.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JogoForca.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JogoForca.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JogoForca().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBLetra;
    private javax.swing.JButton jBPalavra;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JMenu jMAjuda;
    private javax.swing.JMenuItem jMIDica;
    private javax.swing.JMenuItem jMINovoJogo;
    private javax.swing.JMenuItem jMISair;
    private javax.swing.JMenu jMJogo;
    private javax.swing.JMenu jMSair;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTFDica;
    private javax.swing.JTextField jTFLetraUsada;
    private javax.swing.JTextField jTFPalavra;
    private javax.swing.JTextField jTFTentativas;
    private javax.swing.JTextField jTFUltimoPalpite;
    // End of variables declaration//GEN-END:variables

}
